from django.contrib import admin
from django.urls import path,include
from Home.views import *
urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('service/', service, name='service'),
    path('ledger/export/pdf/', ledger_export_pdf, name='ledger_export_pdf'),
    path('ledger/export/word/', ledger_export_word, name='ledger_export_word'),
    path('contact/', contact, name='contact'),
    path('department_list/', department_list, name='department_list'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path ('employee_list/', employee_list, name='employee_list'),
    path('attendance_sheet/', attendance_sheet, name='attendance_sheet'),
path('attendance/save/', save_attendance, name='save_attendance'),
path('attendance/export/', download_attendance, name='download_attendance'),
path('payroll/', payroll_list, name='payroll_list'),
path('payslip/<int:pk>/', payslip_detail, name='payslip_detail'),
path('delete_department/<int:pk>/', delete_department, name="delete_department"),
    path('assets/', asset_list, name='asset_list'),
    path('assets/add/', asset_create_or_edit, name='asset_create'),
    path('employees/edit/<int:pk>/', edit_employee, name='edit_employee'),
    path('employees/delete/<int:pk>/', delete_employee, name='delete_employee'),
    path('employees/toggle-status/<int:pk>/', toggle_employee_status, name='toggle_employee_status'),
    path('assets/edit/<int:pk>/', asset_create_or_edit, name='asset_edit'),
    path('maintenance/', maintenance_list, name='maintenance_list'),
path('maintenance/add/', add_maintenance, name='add_maintenance'),
path('maintenance/add/<int:asset_id>/', add_maintenance, name='add_maintenance_for_asset'),
path('transport/logs/', transport_log_list, name='transport_log_list'),
path('transport/logs/add/', add_transport_log, name='add_transport_log'),
path('farming/', farming_list, name='farming_list'),
path('farming/new/', farming_create_or_edit, name='farming_create'),
path('farming/edit/<int:pk>/', farming_create_or_edit, name='farming_edit'),
path('expenses/', expense_list, name='expense_list'),
path('expenses/add/', expense_create, name='expense_create'),
path('ledger/', ledger_list, name='ledger_list'),
path('ledger/new/', ledger_create, name='ledger_create'),

]